name: Build app and contracts

on:
  push:
    branches: [main, gh-pages]
  pull_request:
    branches: [main, gh-pages]

jobs:
  build-and-test:
    name: Build app and contracts
    runs-on: ubuntu-latest

    steps:
      - name: Work around permission issue
        run: git config --global --replace-all safe.directory '*'
        
      -  uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy default app env
        run: cp .env.example .env
        
      - name: Install submodules
        run: git submodule update --init --recursive
        
      - name: Copy default contracts env
        run: cp src/submodules/fanzone-smart-contracts/.env.example src/submodules/fanzone-smart-contracts/.env

      - name: Build contracts
        run: npm run build-fanzone-contracts

      - name: Build react app
        run: npm run build
